### ISSUE TITLE
Find alternate APT repository

### ISSUE THREAD

**Issue by hectcastro** [azavea/ansible-pcp#3] opened 2017-06-29 18:57 UTC
The packages on Bintray for the Netflix managed repository appear to be gone.

**Comment by tnation14** [comment] 2017-08-21 13:23
APT repo was changed from Netflix OSS repo to its own PCP repo. Duplicate of #1, fixed by #2. Verified in development using the Example VM

**Closed as completed by tnation14** 2017-08-21 13:23 UTC
Labels: operations, size: 1
